<?php

use App\Models\Article;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $articles = Article::factory()->times(3)->create();

    $response = $this->get(route('articles.index'));

    $response->assertOk();
    $response->assertViewIs('article.index');
    $response->assertViewHas('articles', $articles);

    // TODO: perform additional assertions
});

test('show returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $article = Article::factory()->create();

    $response = $this->get(route('articles.show', ['id' => $article->id]));

    $response->assertOk();
    $response->assertViewIs('article.show');
    $response->assertViewHas('article', $article);

    // TODO: perform additional assertions
});

// test cases...
