<?php

use App\Models\Forum;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

test('show returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $forum = Forum::factory()->create();

    $response = $this->get(route('forums.categories.show', ['id' => $id]));

    $response->assertOk();
    $response->assertViewIs('forum.category_topic.index');
    $response->assertViewHas('forum', $forum);

    // TODO: perform additional assertions
});

// test cases...
