<?php

use App\Models\Playlist;
use App\Models\PlaylistTorrent;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

test('destroy returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $playlistTorrent = PlaylistTorrent::factory()->create();

    $response = $this->delete(route('playlists.detach', ['id' => $playlistTorrent->id]));

    $response->assertOk();
    $this->assertModelMissing($playlist);

    // TODO: perform additional assertions
});

test('store returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $playlist = Playlist::factory()->create();

    $response = $this->post(route('playlists.attach'), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

// test cases...
