<?php

use App\Models\Movie;
use App\Models\Torrent;
use App\Models\Tv;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

test('show returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $torrent = Torrent::factory()->create();
    $tv = Tv::factory()->create();
    $movie = Movie::factory()->create();

    $response = $this->get(route('torrents.similar', ['category_id' => $category_id, 'tmdb' => $tmdb]));

    $response->assertOk();
    $response->assertViewIs('torrent.similar');
    $response->assertViewHas('meta');
    $response->assertViewHas('torrent', $torrent);
    $response->assertViewHas('categoryId');
    $response->assertViewHas('tmdbId');

    // TODO: perform additional assertions
});

// test cases...
