<?php

use App\Models\History;
use App\Models\Torrent;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $torrent = Torrent::factory()->create();
    $histories = History::factory()->times(3)->create();

    $response = $this->get(route('history', ['id' => $id]));

    $response->assertOk();
    $response->assertViewIs('torrent.history');
    $response->assertViewHas('torrent', $torrent);
    $response->assertViewHas('history');

    // TODO: perform additional assertions
});

// test cases...
