<?php

use App\Models\Season;
use App\Models\Tv;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

test('show returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $season = Season::factory()->create();
    $tv = Tv::factory()->create();

    $response = $this->get(route('mediahub.season.show', ['id' => $id]));

    $response->assertOk();
    $response->assertViewIs('mediahub.tv.season.show');
    $response->assertViewHas('season', $season);
    $response->assertViewHas('show');

    // TODO: perform additional assertions
});

// test cases...
