<?php

use App\Models\Bot;
use App\Models\User;
use App\Models\UserAudible;
use App\Models\UserEcho;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

test('audibles returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();

    $response = $this->get('api/chat/audibles');

    $response->assertOk();

    // TODO: perform additional assertions
});

test('bot messages returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $bot = Bot::factory()->create();

    $response = $this->get('api/chat/bot/{bot_id}');

    $response->assertOk();

    // TODO: perform additional assertions
});

test('bots returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->get('api/chat/bots');

    $response->assertOk();

    // TODO: perform additional assertions
});

test('config returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->get('api/chat/config');

    $response->assertOk();

    // TODO: perform additional assertions
});

test('create message returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();
    $bots = Bot::factory()->times(3)->create();
    $userEchos = UserEcho::factory()->times(3)->create();
    $userAudibles = UserAudible::factory()->times(3)->create();

    $response = $this->post('api/chat/messages', [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('delete bot echo returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $userEcho = UserEcho::factory()->create();
    $user = User::factory()->create();
    $userEchos = UserEcho::factory()->times(3)->create();

    $response = $this->post('api/chat/echoes/{user_id}/delete/bot', [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('delete message returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->post('api/chat/message/{id}/delete', [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('delete room echo returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $userEcho = UserEcho::factory()->create();
    $user = User::factory()->create();
    $userEchos = UserEcho::factory()->times(3)->create();

    $response = $this->post('api/chat/echoes/{user_id}/delete/chatroom', [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('delete target echo returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $userEcho = UserEcho::factory()->create();
    $user = User::factory()->create();
    $userEchos = UserEcho::factory()->times(3)->create();

    $response = $this->post('api/chat/echoes/{user_id}/delete/target', [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('echoes returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();

    $response = $this->get('api/chat/echoes');

    $response->assertOk();

    // TODO: perform additional assertions
});

test('messages returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->get('api/chat/messages/{room_id}');

    $response->assertOk();

    // TODO: perform additional assertions
});

test('private messages returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->get('api/chat/private/messages/{target_id}');

    $response->assertOk();

    // TODO: perform additional assertions
});

test('rooms returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->get('api/chat/rooms');

    $response->assertOk();

    // TODO: perform additional assertions
});

test('statuses returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->get('api/chat/statuses');

    $response->assertOk();

    // TODO: perform additional assertions
});

test('toggle bot audible returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $userAudible = UserAudible::factory()->create();
    $user = User::factory()->create();
    $userAudibles = UserAudible::factory()->times(3)->create();

    $response = $this->post('api/chat/audibles/{user_id}/toggle/bot', [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('toggle room audible returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $userAudible = UserAudible::factory()->create();
    $user = User::factory()->create();
    $userAudibles = UserAudible::factory()->times(3)->create();

    $response = $this->post('api/chat/audibles/{user_id}/toggle/chatroom', [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('toggle target audible returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $userAudible = UserAudible::factory()->create();
    $user = User::factory()->create();
    $userAudibles = UserAudible::factory()->times(3)->create();

    $response = $this->post('api/chat/audibles/{user_id}/toggle/target', [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('update user chat status returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();

    $response = $this->post('api/chat/user/{id}/status', [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('update user room returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();
    $userEchos = UserEcho::factory()->times(3)->create();

    $response = $this->post('api/chat/user/{id}/chatroom', [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('update user target returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();

    $response = $this->post('api/chat/user/{id}/target', [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

// test cases...
