<?php

use App\Models\Category;
use App\Models\Torrent;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

test('filter returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $torrents = Torrent::factory()->times(3)->create();

    $response = $this->getJson('api/torrents/filter');

    $response->assertOk();
    $response->assertJsonStructure([
        // TODO: compare expected response data
    ]);

    // TODO: perform additional assertions
});

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $torrents = Torrent::factory()->times(3)->create();

    $response = $this->getJson(route('torrents.index'));

    $response->assertOk();
    $response->assertJsonStructure([
        // TODO: compare expected response data
    ]);

    // TODO: perform additional assertions
});

test('show returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $torrent = Torrent::factory()->create();

    $response = $this->getJson('api/torrents/{id}');

    $response->assertOk();
    $response->assertJsonStructure([
        // TODO: compare expected response data
    ]);

    // TODO: perform additional assertions
});

test('store returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $category = Category::factory()->create();
    $user = User::factory()->create();

    $response = $this->postJson('api/torrents/upload', [
        // TODO: send request data
    ]);

    $response->assertOk();
    $response->assertJsonStructure([
        // TODO: compare expected response data
    ]);

    // TODO: perform additional assertions
});

// test cases...
