<?php

use App\Http\Controllers\User\TipController;
use App\Http\Requests\StoreTipRequest;
use App\Models\BonTransactions;
use App\Models\Post;
use App\Models\Torrent;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $bonTransactions = BonTransactions::factory()->times(3)->create();

    $response = $this->get(route('tips.index', ['username' => $username]));

    $response->assertOk();
    $response->assertViewIs('user.tip.index');
    $response->assertViewHas('user');
    $response->assertViewHas('bontransactions');
    $response->assertViewHas('userbon');
    $response->assertViewHas('tips_sent');
    $response->assertViewHas('tips_received');

    // TODO: perform additional assertions
});

test('store returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $torrent = Torrent::factory()->create();
    $post = Post::factory()->create();

    $response = $this->post(route('tips.store', ['username' => $username]), [
        // TODO: send request data
    ]);

    $response->assertRedirect(withSuccess(trans('bon.success-tip')));

    // TODO: perform additional assertions
});

test('store validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        TipController::class,
        'store',
        StoreTipRequest::class
    );
});

// test cases...
