<?php

use App\Models\Torrent;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

test('show returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();
    $torrents = Torrent::factory()->times(3)->create();

    $response = $this->get(route('users.torrent_zip.show', [$user]));

    $response->assertOk();

    // TODO: perform additional assertions
});

// test cases...
