<?php

use App\Http\Controllers\Staff\CategoryController;
use App\Http\Requests\Staff\StoreCategoryRequest;
use App\Http\Requests\Staff\UpdateCategoryRequest;
use App\Models\Category;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

test('create returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->get(route('staff.categories.create'));

    $response->assertOk();
    $response->assertViewIs('Staff.category.create');

    // TODO: perform additional assertions
});

test('destroy returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $category = Category::factory()->create();

    $response = $this->delete(route('staff.categories.destroy', ['id' => $category->id]));

    $response->assertOk();
    $this->assertModelMissing($staff.category);

    // TODO: perform additional assertions
});

test('edit returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $category = Category::factory()->create();

    $response = $this->get(route('staff.categories.edit', ['id' => $category->id]));

    $response->assertOk();
    $response->assertViewIs('Staff.category.edit');
    $response->assertViewHas('category', $category);

    // TODO: perform additional assertions
});

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $categories = Category::factory()->times(3)->create();

    $response = $this->get(route('staff.categories.index'));

    $response->assertOk();
    $response->assertViewIs('Staff.category.index');
    $response->assertViewHas('categories', $categories);

    // TODO: perform additional assertions
});

test('store returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->post(route('staff.categories.store'), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('store validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        CategoryController::class,
        'store',
        StoreCategoryRequest::class
    );
});

test('update returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $category = Category::factory()->create();

    $response = $this->patch(route('staff.categories.update', ['id' => $category->id]), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('update validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        CategoryController::class,
        'update',
        UpdateCategoryRequest::class
    );
});

// test cases...
