<?php

use App\Models\History;
use App\Models\Message;
use App\Models\Peer;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

test('chat returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $messages = Message::factory()->times(3)->create();

    $response = $this->post(route('staff.flush.chat'), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('peers returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $history = History::factory()->create();
    $peers = Peer::factory()->times(3)->create();

    $response = $this->post(route('staff.flush.peers'), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

// test cases...
