<?php

use App\Http\Controllers\Staff\NoteController;
use App\Http\Requests\Staff\StoreNoteRequest;
use App\Models\Note;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

test('destroy returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $note = Note::factory()->create();
    $user = User::factory()->create();

    $response = $this->delete(route('staff.notes.destroy', ['id' => $note->id]));

    $response->assertOk();
    $this->assertModelMissing($staff.note);

    // TODO: perform additional assertions
});

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



    $response = $this->get(route('staff.notes.index'));

    $response->assertOk();
    $response->assertViewIs('Staff.note.index');

    // TODO: perform additional assertions
});

test('store returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = User::factory()->create();
    $note = Note::factory()->create();

    $response = $this->post(route('staff.notes.store', ['username' => $note->username]), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

test('store validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        NoteController::class,
        'store',
        StoreNoteRequest::class
    );
});

// test cases...
