<?php

use App\Models\Seedbox;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

test('destroy returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $seedbox = Seedbox::factory()->create();

    $response = $this->delete(route('staff.seedboxes.destroy', ['id' => $seedbox->id]));

    $response->assertOk();
    $this->assertModelMissing($staff.seedbox);

    // TODO: perform additional assertions
});

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $seedboxes = Seedbox::factory()->times(3)->create();

    $response = $this->get(route('staff.seedboxes.index'));

    $response->assertOk();
    $response->assertViewIs('Staff.seedbox.index');
    $response->assertViewHas('seedboxes', $seedboxes);

    // TODO: perform additional assertions
});

// test cases...
